Add documentation for certificates and access restrictions
mendix/cf-mendix-buildpack pull request #486
Opened 2021-11-25 16:31 UTC by markbastiaans

This PR adds documentation for `CLIENT_CERTIFICATES` and `ACCESS_RESTRICTIONS`, and improves documentation for `CERTIFICATE_AUTHORITIES`.

2021-12-02 14:46 UTC, cwesdorp requested changes

2021-12-02 14:46 UTC, cwesdorp commented on README.md
> +The contents of this variable should be a concatenated string containing a the additional CAs in [PEM format](https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail) that are trusted.
Should we mention that the certificate chain needs to be added if the certificate to check is signed by an intermediate?

2021-12-02 14:46 UTC, cwesdorp commented on README.md
> +The buildpack ensures that the environment variable is converted into custom runtime settings, and client certificate support is dependent on runtime support. Please consult the [runtime documentatio
I would be in favor of a deeplink to the page (https://docs.mendix.com/howto/integration/use-a-client-certificate). Verified with docs team, they crosscheck links between Mendix docs pages.

2021-12-03 09:29 UTC, cwesdorp approved these changes

2021-12-03 12:34 UTC, svanderburg approved these changes

2021-12-03 12:34 UTC, merged